name: CI

on: [push]

jobs:
  send:
    runs-on: ubuntu-latest
    name: Send message to Teamwork Chat
    steps:
    - name: Send Text
      uses: aidangrabe/slack-post-action@v1.5
      with:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        MESSAGE: "GO TEST"
