name: CI

on: 
  pull_request:
    types: [closed, opened]

jobs:
  send:
    runs-on: ubuntu-latest
    name: Send message to Teamwork Chat
    steps:
    - name: Send Text
      uses: aidangrabe/chat-pr-github-action@v1.15
      with:
        CHAT_HOOK_URL: ${{ secrets.CHAT_HOOK_URL }}
