name: CI

on: 
  pull_request:
    types: [closed, opened]

jobs:
  send:
    runs-on: ubuntu-latest
    name: Send message to Teamwork Chat
    steps:
    - name: Send Text
      uses: aidangrabe/slack-post-action@v1.13
      with:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        MESSAGE: "GO TEST"
